const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const code = fs.readFileSync(require('node:path').join(__dirname, '../public/assets/app.js'), 'utf8');
const escape = code.split('\n').find(line => line.startsWith('const esc ='));
const start = code.indexOf('async function openSearchLog(id)');
const end = code.indexOf('async function renderAdmin()', start);
const target = { innerHTML: '', querySelector: () => ({ addEventListener() {} }) };
const row = { name: '<img src=x onerror=alert(1)>', size_bytes: 3e9, seeders: 10, engine: '<script>bad</script>', link_type: 'Magnet', status: 'model', candidate_id: 't_one', reason: 'Sent to model', note: 'Audio assumed' };
const report = { outcome: 'no_selection', query: '<script>query</script>', media: { title: 'The Wire' }, filters: { received: 1, sent_to_model: 1, reasons: {}, rows: [row] }, decision: { model_called: true, model: 'test', summary: '<script>summary</script>', selected: [], audio_policy: 'Assume original audio', evaluations: [{ candidate_id: 't_one', verdict: 'rejected', reason: '<script>rejection</script>' }] } };
const context = vm.createContext({ document: { querySelector: () => target }, state: { user: { role: 'admin' } }, searchLogDialog: { open: true }, bindClose() {}, icon: () => '', api: async () => ({ logs: [{ created_at: 1, report }] }) });
vm.runInContext(escape + '\n' + code.slice(start, end), context);
(async () => {
  await vm.runInContext('openSearchLog(4)', context);
  assert(target.innerHTML.includes('Model rejected'));
  assert(target.innerHTML.includes('&lt;script&gt;rejection&lt;/script&gt;'));
  assert(!target.innerHTML.includes('<script>') && !target.innerHTML.includes('<img src=x'));
  report.decision.evaluations[0].verdict = 'alternative';
  await vm.runInContext('openSearchLog(4)', context);
  assert(target.innerHTML.includes('Eligible alternative; not chosen'));
  delete report.decision.evaluations;
  await vm.runInContext('openSearchLog(4)', context);
  assert(target.innerHTML.includes('No candidate-specific reason returned'));
  report.outcome = 'selected'; report.decision.selected = [{ candidate_id: 't_one', quality: '720p', confidence: .95, reason: 'Chosen' }];
  await vm.runInContext('openSearchLog(4)', context);
  assert(target.innerHTML.includes('Selected and validated'));
  assert(!target.innerHTML.includes('No candidate-specific reason returned'));
  console.log('PASS: 7 diagnostics rendering/escaping checks using the actual app renderer.');
})().catch(error => { console.error(error); process.exitCode = 1; });
